//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khareedo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SupplierPayment
    {
        public int SupplierPaymentID { get; set; }
        public Nullable<int> invoiceId { get; set; }
        public Nullable<int> Supplier { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentTerm { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<decimal> Totalamount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string Sup { get; set; }
    }
}
